name: sybil2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aom=3.6.1
  - asttokens=3.0.0
  - attr=2.5.1
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.11
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ffmpeg=4.4.2
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gdcm=2.8.9
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - intel-openmp=2022.0.1
  - ipykernel=6.29.5
  - ipython=8.31.0
  - ipywidgets=8.1.8
  - jedi=0.19.2
  - jinja2=3.1.5
  - json-c=0.17
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyterlab_widgets=3.0.16
  - keyutils=1.6.1
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libcap=2.71
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20240808
  - libegl=1.7.0
  - libevent=2.1.12
  - libexpat=2.6.4
  - libfabric=2.0.0
  - libfabric1=2.0.0
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libhwloc=2.11.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpciaccess=0.18
  - libpmix=5.0.6
  - libpng=1.6.44
  - libsodium=1.0.20
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libudev1=256.9
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.22.0
  - libvpx=1.13.1
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lightning=2.5.0.post0
  - lightning-utilities=0.11.9
  - llvm-openmp=15.0.7
  - lz4-c=1.10.0
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpi=1.0
  - mpmath=1.3.0
  - nccl=2.23.4.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.4.2
  - openh264=2.3.1
  - openjpeg=2.5.3
  - openmpi=5.0.6
  - openssl=3.6.0
  - p11-kit=0.24.1
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytorch-cuda=12.4
  - pytorch-lightning=2.5.0.post0
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - rdma-core=55.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.6.0
  - six=1.17.0
  - stack_data=0.6.3
  - svt-av1=1.4.1
  - tk=8.6.13
  - torchaudio=2.5.1
  - torchmetrics=1.6.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - ucc=1.3.0
  - ucx=1.17.0
  - urllib3=2.3.0
  - wayland=1.23.1
  - wayland-protocols=1.37
  - wcwidth=0.2.13
  - wheel=0.45.1
  - widgetsnbextension=4.0.15
  - x264=1!164.3095
  - x265=3.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.0
      - acvl-utils==0.2.5
      - alabaster==1.0.0
      - albucore==0.0.24
      - albumentations==2.0.7
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - antspyx==0.6.1
      - argparse==1.4.0
      - attrs==25.3.0
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - babel==2.17.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - beautifulsoup4==4.14.2
      - black==25.1.0
      - blosc2==3.6.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - comet-ml==3.49.10
      - configobj==5.0.9
      - confseq==0.0.11
      - connected-components-3d==3.24.0
      - contourpy==1.3.2
      - coral-pytorch==1.4.0
      - coverage==7.13.1
      - cycler==0.12.1
      - deprecated==1.2.18
      - detectron2==0.6
      - dill==0.4.0
      - docutils==0.21.2
      - duckdb==1.2.1
      - dulwich==0.22.8
      - dynamic-network-architectures==0.4.2
      - easydict==1.13
      - ecos==2.0.14
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - everett==3.1.0
      - fancycompleter==0.11.1
      - fastjsonschema==2.21.1
      - fastremap==1.17.4
      - fft-conv-pytorch==1.2.0
      - fill-voids==2.1.1
      - fonttools==4.58.0
      - formulaic==1.1.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - gputil==1.4.0
      - greenlet==3.2.3
      - grpcio==1.72.1
      - h5py==3.13.0
      - hf-xet==1.1.3
      - huggingface-hub==0.32.4
      - humanize==4.12.3
      - hydra-core==1.3.2
      - idc-index==0.9.0
      - idc-index-data==21.0.0
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - imagesize==1.4.1
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - interface-meta==1.3.0
      - iopath==0.1.9
      - itk==5.4.5
      - itk-core==5.4.5
      - itk-filtering==5.4.5
      - itk-io==5.4.5
      - itk-numerics==5.4.5
      - itk-registration==5.4.5
      - itk-segmentation==5.4.5
      - joblib==1.5.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2025.4.1
      - kiwisolver==1.4.8
      - kornia==0.7.4
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - lifelines==0.30.0
      - linecache2==1.0.0
      - loguru==0.7.3
      - lungmask==0.2.20
      - lxml==5.4.0
      - lz4==4.4.5
      - markdown==3.8
      - markdown-it-py==3.0.0
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - monai==1.5.0
      - more-itertools==10.8.0
      - msgpack==1.1.1
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - narwhals==1.45.0
      - nbformat==5.10.4
      - ndindex==1.10.0
      - nibabel==5.3.2
      - nilearn==0.11.1
      - nltk==3.9.1
      - nninteractive==1.0.1
      - nnunetv2==2.6.2
      - numexpr==2.11.0
      - numpy==1.24.1
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.10.18
      - osqp==0.6.7.post3
      - p-tqdm==1.4.2
      - pandas==2.2.3
      - pathos==0.3.4
      - pathspec==0.12.1
      - patsy==1.0.1
      - plotille==5.0.0
      - plotly==6.2.0
      - pluggy==1.6.0
      - portalocker==3.1.1
      - pox==0.3.6
      - ppft==1.7.7
      - protobuf==6.31.1
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pybind11==3.0.1
      - pycocotools==2.0.9
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pydicom==3.0.1
      - pylibjpeg==2.1.0
      - pylibjpeg-libjpeg==2.3.0
      - pylidc==0.2.3
      - pyparsing==3.2.3
      - pyrepl==0.11.3.post1
      - pytest==8.4.2
      - pytest-cov==7.0.0
      - python-box==6.1.0
      - python-graphviz==0.21
      - pytz==2025.2
      - qdldl==0.1.7.post5
      - rad-vision-engine==1.0.0
      - referencing==0.36.2
      - regex==2024.11.6
      - remote-pdb==2.1.0
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - roman-numerals-py==3.1.0
      - rpds-py==0.25.0
      - s5cmd==0.2.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scikit-survival==0.24.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.28.0
      - shellingham==1.5.4
      - simpleitk==2.5.0
      - simplejson==3.20.1
      - simsimd==6.2.1
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - soupsieve==2.8
      - sphinx==8.2.3
      - sphinx-click==6.0.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - sqlalchemy==2.0.41
      - statsmodels==0.14.5
      - stringzilla==3.12.5
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.6.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.12
      - tokenizers==0.21.1
      - torch==2.7.1
      - torch-scatter==2.1.2+pt27cu126
      - torchio==0.20.8
      - torchsurv==0.1.4
      - torchvision==0.22.1
      - traceback2==1.4.0
      - transformers==4.47.1
      - triton==3.3.1
      - typer==0.15.4
      - typing-inspection==0.4.0
      - unittest2==1.1.0
      - webcolors==24.11.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wurlitzer==3.1.1
      - yacs==0.1.8
